export const Item = {
    worn_sword: {
        type: 'weapon',
        name: '破爛的劍',
        depiction: '這把劍曾經輝煌，但現在已經受損。雖然失去了一些光澤，但或許在冒險中仍能派上用場。',
        ATK: 1,
        shop_buy: 5,
    },
    wood_sword: {
        type: 'weapon',
        name: '木劍',
        depiction: '簡單而輕巧的木劍，是初次冒險的選擇。雖然不及鐵劍堅固，但足以應對一些較弱的敵人。',
        ATK: 3,
        shop_buy: 15,
    },
    iron_sword: {
        type: 'weapon',
        name: '鐵劍',
        depiction: '一把堅固的鐵劍，刀刃鋒利，適合在冒險中應對各種怪物。它會是你在旅途中的可靠夥伴。',
        ATK: 5,
        shop_buy: 40,
    },
    bronze_long_sword: {
        type: 'weapon',
        name: '青銅長劍',
        depiction: '簡約而堅固，劍身呈深邃的青銅色。輕盈的揮舞中彰顯冒險者的力量。',
        ATK: 8,
        shop_buy: 90,
    },
    steel_broad_sword: {
        type: 'weapon',
        name: '鋼製闊劍',
        depiction: '威猛的鋼製闊劍，劍刃寬厚而鋒利。適合熟練戰士，能輕鬆應對不同的戰鬥場景。',
        ATK: 12,
        shop_buy: 150,
    },
    slime: {
        type: 'food',
        name: '史萊姆黏液',
        depiction: '這份粘滑的物質來自史萊姆，具有神秘的魔法力量。你不知道它吃起來如何，恐怕你也不會想知道。',
    },
    slime_pacifier: {
        type: 'loot',
        name: '寶寶史萊姆的奶嘴',
        depiction: '一個柔軟的、可咬的奶嘴，專為人類的小寶寶而設計。但為什麼史萊姆會有這種東西呢？',
    },
    S_red_potion: {
        type: 'potion',
        name: '小瓶紅色藥水',
        depiction: '小瓶裝的紅色藥水。適合快速急救。恢復少量生命，是冒險旅途中的便攜夥伴。',
        shop_buy: 5,
        effect: { hp: 50, },
    },
    M_red_potion: {
        type: 'potion',
        name: '中瓶紅色藥水',
        depiction: '中瓶裝的紅色藥水。提供較大幅度的生命回復，是長時間冒險的理想選擇。',
        shop_buy: 15,
        effect: { hp: 200, },
    },
    L_red_potion: {
        type: 'potion',
        name: '大瓶紅色藥水',
        depiction: '大瓶裝的紅色藥水。適合快速急救。能在極短時間內回復大量生命，是面對強敵時的生死關鍵。',
        shop_buy: 30,
        effect: { hp: 500, },
    },
    exp_potion: {
        type: 'potion',
        name: '經驗藥水',
        depiction: '充滿神秘力量的藥水，可以讓你變強。',
        shop_buy: 1,
        effect: { exp: 500, },
    },
}