export const Monster = {
    slime_baby: {
        name: '寶寶史萊姆',
        hp: 1,
        attack: 0,
        exp: 1,
        gold: 1,
        loot: ['slime_pacifier'],
        text: ['<p>一個剛剛誕生的小生物，它滿是好奇心，眨著大大的眼睛看著你。他似乎毫無威脅，只是在探索這個新的環境，可能還會偶爾發出軟弱的啾聲。面對這樣一個天真無辜的生命，你真的要消滅他嗎？</p>'],
    },
    slime_green: {
        name: '綠色史萊姆',
        hp: 5,
        attack: 4,
        exp: 4,
        gold: 2,
        loot: [''],
        text: [''],
    },
    slime_blue: {
        name: '藍色史萊姆',
        hp: 20,
        attack: 7,
        exp: 12,
        gold: 4,
        loot: [''],
        text: [''],
    },
    slime_purple: {
        name: '紫色史萊姆',
        hp: 50,
        attack: 12,
        exp: 26,
        gold: 6,
        loot: [''],
        text: [''],
    },
    slime_orange: {
        name: '橘色史萊姆',
        hp: 100,
        attack: 22,
        exp: 36,
        gold: 8,
        loot: [''],
        text: [''],
    },
    slime_red: {
        name: '紅色史萊姆',
        hp: 200,
        attack: 31,
        exp: 50,
        gold: 10,
        loot: [''],
        text: [''],
    },
    slime_Boss: {
        name: '史萊姆國王',
        hp: 700,
        attack: 60,
        exp: 500,
        gold: 100,
        loot: [],
        text: [''],
    },
    // slime_pink: {
    //     name: '粉色史萊姆',
    //     hp: ,
    //     attack: ,
    //     exp: ,
    //     gold: ,
    //     loot: [],
    //     text: [''],
    // },
}